<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Inactive' => '',
    'Update Admin' => '',
    'View Admin' => '',
    'Auth Key' => '',
    'Created At' => 'Добавлено',
    'Email' => '',
    'Email Confirm Token' => '',
    'First Name' => 'Имя',
    'ID' => 'ID',
    'Last Name' => 'Фамилия',
    'Password Hash' => '',
    'Password Reset Expire' => '',
    'Password Reset Token' => '',
    'Role' => 'Роль',
    'Status' => 'Статус',
    'Updated At' => 'Редактировано',
    'Active' => 'Активный',
    'Admin' => 'Администратор',
    'Admins' => 'Администраторы',
    'Create' => 'Создать',
    'Create Admin' => 'Добавить Администратора',
    'Dashboard' => 'Панель управления',
    'Delete' => 'Удалить',
    'Incorrect username or password.' => 'Неправильный пароль',
    'Logout' => 'Выход',
    'New Password' => 'Новый пароль',
    'New Password Repeat' => 'Повторить пароль',
    'Password' => 'Пароль',
    'Please Sign In' => 'Пожалуйста, войдите',
    'Remember Me' => 'Запомнить',
    'Reset' => 'Сброс',
    'Search' => 'Поиск',
    'Sign in' => 'Вход',
    'Update' => 'Редактировать',
    'Username' => 'Логин',
];
