<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Admin' => '',
    'Admins' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Create' => '',
    'Create Admin' => '',
    'Created At' => '',
    'Dashboard' => '',
    'Delete' => '',
    'Email' => '',
    'Email Confirm Token' => '',
    'First Name' => '',
    'ID' => '',
    'Inactive' => '',
    'Incorrect username or password.' => '',
    'Last Name' => '',
    'Logout' => '',
    'New Password' => '',
    'New Password Repeat' => '',
    'Password' => '',
    'Password Hash' => '',
    'Password Reset Expire' => '',
    'Password Reset Token' => '',
    'Please Sign In' => '',
    'Remember Me' => '',
    'Reset' => '',
    'Role' => '',
    'Search' => '',
    'Sign in' => '',
    'Status' => '',
    'Update' => '',
    'Update Admin' => '',
    'Updated At' => '',
    'Username' => '',
    'View Admin' => '',
];
