<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активний',
    'Admin' => 'Адміністратор',
    'Admins' => 'Адміністратори',
    'Are you sure you want to delete this item?' => 'Ви впевнені, що хочете видалити цей запис?',
    'Auth Key' => '',
    'Create' => 'Створити',
    'Create Admin' => 'Додати Адміністратора',
    'Created At' => 'Додано',
    'Dashboard' => 'Панель керування',
    'Delete' => 'Видалити',
    'Email' => '',
    'Email Confirm Token' => '',
    'First Name' => 'Ім\'я',
    'ID' => '',
    'Inactive' => 'Неактивний',
    'Incorrect username or password.' => 'Неправильний логін або пароль',
    'Last Name' => 'Прізвище',
    'Logout' => 'Вихід',
    'New Password' => 'Новий пароль',
    'New Password Repeat' => 'Повтор пароля',
    'Password' => 'Пароль',
    'Password Hash' => '',
    'Password Reset Expire' => '',
    'Password Reset Token' => '',
    'Please Sign In' => 'Будь ласка, увійдіть',
    'Remember Me' => 'Запам\'ятати мене',
    'Reset' => 'Скинути',
    'Role' => 'Роль',
    'Search' => 'Пошук',
    'Sign in' => 'Вхід',
    'Status' => 'Статус',
    'Update' => 'Оновити',
    'Update Admin' => 'Редагувати',
    'Updated At' => 'Редаговано',
    'Username' => 'Логін',
    'View Admin' => 'Переглянути',
];
